# action.yml
name: "Keycloak Add/Delete Redirect"
description: "Add or delete Keycloak redirects"
branding:
  icon: "lock"
  color: "blue"
inputs:
  add_delete:
    description: "Add or delete: [add|del]"
    required: true
  redirect:
    description: "Redirect url to add or delete"
    required: true
  secret:
    description: "Token"
    required: true
  clientid:
    description: "Client to authenticate from"
    default: "fom-admin"
    required: false
  clientid_2:
    description: "Client to apply changes to"
    default: "fom"
    required: false
  realm:
    description: "Realm to authenticate from"
    default: "ichqx89w"
    required: false
  host:
    description: "Host to authenticate from"
    default: "https://dev.oidc.gov.bc.ca"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.add_delete }}
    - ${{ inputs.redirect }}
    - ${{ inputs.secret }}
    - ${{ inputs.clientid }}
    - ${{ inputs.clientid_2 }}
    - ${{ inputs.realm }}
    - ${{ inputs.host }}
