on: [push]

jobs:
  run-redirect-test:
    runs-on: ubuntu-latest
    environment:
      name: dev
    name: Add a redirect url
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add
        uses: ./
        id: add
        with:
          add_delete: "add"
          redirect: "https://google.com"
          secret: ${{ secrets.KC_SECRET }}
          clientid: ${{ secrets.KC_CLIENTID }}
          clientid_2: "fom"
          realm: ${{ secrets.KC_REALM }}
          host: ${{ secrets.KC_HOST }}
      - name: Output
        run: |
          echo "Output: ${{ steps.id }}"
